### ISSUE TITLE
500 - Internal Server Error while calling with name/tag which don't exist

### ISSUE THREAD

**Issue by tbitowt** [Henrik-3/unofficial-valorant-api#10]
While calling several endpoint with the name/tag which don't exist the real status is `500 - Internal Server Error` with the data like:
```{
    "status": "404",
    "message": "User not found"
}
```

List of endpoints with the issue which I checked:
- mmr-history
- live-match
- matches v3

At least `mmr` and `puuid` returns 404, which should be right result I think.

**Comment by Henrik-3** [comment]
Fixed
