### ISSUE TITLE
Issue when calling /valorant/v1/puuid/{name}/{tag}

### ISSUE THREAD

**Issue by Lunium** [Henrik-3/unofficial-valorant-api#11]
I'm having an issue when calling /valorant/v1/puuid/{name}/{tag}.

For instance if I do this call with ScreaM's account (Liquid ScreaM#TAP) I get a 500 status code response.
I've tried both with and without encoding it:
-  /valorant/v1/puuid/Liquid ScreaM/TAP
- /valorant/v1/puuid/Liquid%20ScreaM/TAP

Both of them don't work. Maybe you can give a better insight as to what I'm doing wrong or maybe this is a bug in the api.
It definitely has something to do with the space in someone's name.

**Comment by Lunium** [comment]
The issue has nothing to do with the space in someone's name. The problem only occurs when a player has too many friend requests. Which in this is case is true as ScreaM has too many of them.

**Comment by Henrik-3** [comment]
Fixed, explaining of the issue is above. Error will be displayed under a 409 error code
