### ISSUE TITLE
Region bug

### ISSUE THREAD

**Issue by HighError** [Henrik-3/unofficial-valorant-api#13]
My nickname: HighError
My tag: Owo
My region: EU

While testing API, I accidentally entered the wrong region, but API did not return an error or result.
If you try to complete the request through a browser, the page will not load.
For example:
https://api.henrikdev.xyz/valorant/v1/mmr/na/HighError/owo

**Comment by Henrik-3** [comment]
It returns 204 because it don't find any competitive matches by that puuid in that region
