### ISSUE TITLE
MMR and PUUID Commands return 500 - Unkown error occured

### ISSUE THREAD

**Issue by hyp3ractive** [Henrik-3/unofficial-valorant-api#14]

**Comment by Henrik-3** [comment]
Can u give me some more details, like Riot ID and stuff

**Comment by hyp3ractive** [comment]
Riot ID was ploo#ful, but I checked with all ID's I know off the top of my head and none of them worked.

**Comment by Henrik-3** [comment]
Issue fixed, return now 409 correctly
