### ISSUE TITLE
/valorant/v3/matches/ returning 1  instead of a json value

### ISSUE THREAD

**Issue by ExceedFlame** [Henrik-3/unofficial-valorant-api#15]
URL with my user & tag:  https://api.henrikdev.xyz/valorant/v3/matches/ap/exceedflame/jett

Also, another bug, for `/valorant/v3/matches/`,  `data[1].match.teams.blue.has_won` most of the time returns `null` 
only `data[0].match.teams.blue.has_won` returns a Boolean but other matches in data[] don't

**Comment by Henrik-3** [comment]
Hey, thanks for the report. I received currently many bugs because of the Recode I made a couple weeks ago. I will take a look at it after breakfast :)

**Comment by Henrik-3** [comment]
@ExceedFlame Bug is fixed, really bad mistake on my side. The reason why sometimes hasWon is null is, because it is deathmatch, where is no team winner, just an individual one

**Comment by ExceedFlame** [comment]
Oh, thank you

**Comment by ExceedFlame** [comment]
I also wanted to ask how can I get the weapon image  by the `damage_weapon_id`  (got from `rounds[0].player_stats[0].kill_events.damage_weapon_id`

**Comment by Henrik-3** [comment]
U can use https://media.valorant-api.com/weapons/{damage_weapon_id}/displayicon.png, probably will add this in the future as a new json object

**Comment by ExceedFlame** [comment]
Ok. Thank you so much
