### ISSUE TITLE
/valorant/v2/mmr/  endpoint stopped working after new valorant patch

### ISSUE THREAD

**Issue by ExceedFlame** [Henrik-3/unofficial-valorant-api#16]
It returns `{"status":"404","message":"User not found"}` everytime for users it used to work with before

**Comment by Henrik-3** [comment]
Hey, I already thought that this will happen, I'm currently in school, I fix it in a like 3 hours when I'm home

Henrik

**Comment by Henrik-3** [comment]
Issue was fixed (Wrong Game Version Number, weird error) and i also added support for the current season.

Henrik
