### ISSUE TITLE
Internal Server Error with the "/valorant/v1/content" Endpoint

### ISSUE THREAD

**Issue by stratrepo-shankha** [Henrik-3/unofficial-valorant-api#18]
I am Getting a - 

**statusCode: 500
error: "Internal Server Error"
message: "error handler is not defined"**

for the "https://api.henrikdev.xyz/valorant/v1/content" endpoint

**Comment by Henrik-3** [comment]
Hey @stratrepo-shankha, this issue should be fixed. I'm sorry for the inconveniences :D
