### ISSUE TITLE
Please return ``status`` and ``data`` in the new endpoint!

### ISSUE THREAD

**Issue by 5late** [Henrik-3/unofficial-valorant-api#19]
Current response of the API is this:
```
{
"puuid":"01066651-f9b0-55c0-8d3d-674c65351821",
"region":"na",
"account_level":15
}
```
However if the account does not exist, it redirects to a different error page. 
Would it be possible to return the data like this:
```
{
"status": "200",
"data": {
    "puuid":"01066651-f9b0-55c0-8d3d-674c65351821",
    "region":"na",
    "account_level":15
}
}
```
So it is more consistent with other API endpoints as well as being easier to check ``status`` codes? 

Thanks, 

- ~5late

**Comment by Henrik-3** [comment]
Thanks for the correction, forgot that :D

**Comment by 5late** [comment]
Thanks!
