### ISSUE TITLE
error on /valorant/v1/account/ endpoint

### ISSUE THREAD

**Issue by ExceedFlame** [Henrik-3/unofficial-valorant-api#21]
`{"statusCode":500,"error":"Internal Server Error","message":"Cannot read property 'MatchID' of undefined"}`

**Comment by Henrik-3** [comment]
Do u have a name where the error occurs?

**Comment by ExceedFlame** [comment]
> Do u have a name where the error occurs?

https://api.henrikdev.xyz/valorant/v1/account/exceedflame/epic

**Comment by Henrik-3** [comment]
Issue should be resolved
