### ISSUE TITLE
Add username in result

### ISSUE THREAD

**Issue by eeeAAAkkk** [Henrik-3/unofficial-valorant-api#22]
Any chance to add the username in the result when fetching by puuid?

**Comment by Henrik-3** [comment]
Hey, about which by-puuid endpoint we talk about? v3/matches or v1/mmr?

**Comment by eeeAAAkkk** [comment]
/valorant/v1/account/
/valorant/v1/by-puuid/mmr/

Would love to have it in these two. I know you are requesting the account with user + tag but you could call the api with all lowercase. I want to have the name like it would be ingame.

**Comment by Henrik-3** [comment]
I will take a look at it, but i'm not sure when i add it

**Comment by p0thi** [comment]
Push.
I would also love to have that! :smiley:

**Comment by p0thi** [comment]
Btw: Is there a public repo for the code of this API? I would love to contribute.

**Comment by Henrik-3** [comment]
Hey, i would both of u ask to take a look at the response of both endpoints. I also added it to the by-puuid/match endpoint :D

In regards to contributions, i have currently many secret keys etc in my API (the API u see is just a part of it) so i would have to seperate the Github code from the code i have in Visual Studio, which is no problem don't get me wrong, but some time that i waste with that which i currently do not have. In one week i have holidays, i could take a look at it then :D

**Comment by eeeAAAkkk** [comment]
looks good. not sure if i would keep it in the match, because you have all the player details in the subelements.

the only thing that i could think off right now would be the account level in the match for the players.

by any chance do you know why the received damage in the match is always 0?

**Comment by p0thi** [comment]
Yep, looks good. thanks for that!
I don't mind having it in the matches endpoint. It is nice to have it in the top level. I would keep it, if it does not add extra work for the endpoint.

**Comment by p0thi** [comment]
Maybe add it to the mmr/region/name/tag endpoint too, just to be consistent.

**Comment by Henrik-3** [comment]
Hey, yeah sure I will add it there too. I was busy the last days with my other big project so I was not that active the last days. Will add this in the next 24-48 hours.

**Comment by Henrik-3** [comment]
Yes i know, i saif two days, now it's three days. Feature is implemented :D
