### ISSUE TITLE
``https://api.henrikdev.xyz/valorant/v1/account/{name}/{tag}`` returns 404 with "no account region found" 

### ISSUE THREAD

**Issue by 5late** [Henrik-3/unofficial-valorant-api#24]
As title says, requesting to ``https://api.henrikdev.xyz/valorant/v1/account/{name}/{tag}`` returns a 404 error with the message:
```
"Found no region for User"
```
Is there a specific region I must put in the request URL, or is this different bug?

Thanks,

- ~5late

**Comment by Henrik-3** [comment]
Hey, i need some more information about the user u requested, what is his name and do u know on which servers he normally plays (europe, america etc.) and has the player already played VALORANT or just League for example ?

**Comment by 5late** [comment]
Hey,

It happens with multiple people all from the NA region.

``Legendgae#pog``
``Exterminator#9366``
+ some others.

All people are from NA region, and with all it returns the same error message as in my original post:
```
"Found no region for User"
```

Thanks,
- ~5late

**Comment by Henrik-3** [comment]
Hey, with out testing the code seems to be fine, also it works when i query matches for the users. I have to go to my club now playing some soccer, when i come home i debug whats wrong, hopefully fix it and text u here again :D

Henrik

**Comment by Henrik-3** [comment]
Thanks for the report btw :D

**Comment by 5late** [comment]
Yeah no problem lol, thanks for you help ;)

**Comment by Henrik-3** [comment]
Issue fixed, i adjusted the database handling and forgot to adjust it at this endpoint :D
