### ISSUE TITLE
API randomly returns ``500 - Unknown error occured``

### ISSUE THREAD

**Issue by 5late** [Henrik-3/unofficial-valorant-api#25]
Some accounts return error code 500.

I'm not sure if the accounts have played only VALORANT or have played other games like League.

Region is NA.

Some accounts:

``Sinon#あやめ``
``lke#ik3``
``rbzkaos#ezz``
``Y Deld S#PBE``

Any clue what could be causing this?

Thanks,

- ~5late

**Comment by Henrik-3** [comment]
Should be resolved, the Bot Account had to many outgoing friend requests, should add an automation for removing them

**Comment by 5late** [comment]
Thank you very much, as far as I've tested it has been working. Will let you know if problem arises again.

- ~5late
