### ISSUE TITLE
valorant/v1/mmr-history/na/ returns 404 for certain user

### ISSUE THREAD

**Issue by 5late** [Henrik-3/unofficial-valorant-api#27]
I'm requesting /valorant/v1/mmr-history/na/azula/6 god and its returning 404, although I am sure the player exists (and other endpoints like /account are working).

- The player does not play League
- It used to work for the player
- The endpoint works for other users

Thanks for help,

- ~5late

**Comment by Henrik-3** [comment]
Fixed, another encoding error ^^
