### ISSUE TITLE
Getting 'Remote Server Returned Code 503' when i try to get info from the Las server

### ISSUE THREAD

**Issue by Danieedu** [Henrik-3/unofficial-valorant-api#29]
Hello i'm using the Api to get the info of the user  lºxºl#las 
Through the link https://api.henrikdev.xyz/valorant/v1/mmr/na/l%C2%BAx%C2%BAl/las 
Using the comand $(urlfetch json https://api.henrikdev.xyz/valorant/v1/mmr/na/l%C2%BAx%C2%BAl/las) to later filter it using Json and showing it as part of a twitch command 
But now i am getting the answer "Remote Server Returned Code 503" instead of the info i was getting 2-3 weeks ago
I guess is a problem in the Las server but there is anything in my side i can try to fix that problem?
I apologize for the lack of technical language and/or other terms, i am farly new in all this (i just created this account) and your API is the first one i use for a real application

**Comment by Henrik-3** [comment]
Hey, it was an issue on my side. Issue should be fixed now :D

**Comment by Danieedu** [comment]
Is fixed indeed! thanks for the fast response and for maintaining this great tool
