### ISSUE TITLE
attempting to get /valorant/v1/mmr/na/ returns "cannot GET" if user is unrated

### ISSUE THREAD

**Issue by colinhartigan** [Henrik-3/unofficial-valorant-api#3]
example: https://api.henrikdev.xyz/valorant/v1/mmr/na/koob85/00085, maybe have it return error code instead?

**Comment by Henrik-3** [comment]
Which HTTP Code should i pick in your opinion, 404 is reserved for "User not found" and i don't really like duplicate error codes because it is harder to handle on the client side
