### ISSUE TITLE
New endpoint idea

### ISSUE THREAD

**Issue by kratosator** [Henrik-3/unofficial-valorant-api#30]
Match history API works great, but its content is quite large in terms of size (I see on average 1.5MB).
It would be nice to add new endpoint which contains only last 5 match UIDs (and maybe other basic information) in order to get a much smaller response.
My use case it to keep track of matches of a user, with this new endpoint I can query periodially for new matches UID and only when a new match is recorded I can make a single request with new match UID (saving a ton of network traffic for both me and your servers).

**Comment by Henrik-3** [comment]
Hey, yeah that would be a nice idea. I plan to create a couple of endpoints where the raw data from the Riot Servers are returned, also one where just the matchlist gets returned in a array (MatchID, Date and another thing i can't remember). Currently i working for some stuff for school, but i will definitly creare these endpoints in the next few days/weeks :D

**Comment by Henrik-3** [comment]
@kratosator Take a look at v1.7.1 https://github.com/Henrik-3/unofficial-valorant-api/releases/tag/v1.7.1

**Comment by kratosator** [comment]
Awesome new endpoint, thank you!
