### ISSUE TITLE
Filter Matches by Maps

### ISSUE THREAD

**Issue by notBradPitt** [Henrik-3/unofficial-valorant-api#31]
I'm wondering if it's possible to check the past few matches based on maps. I'm trying to see my performance on each map

**Comment by Henrik-3** [comment]
I will check that, but that should be possible yes, i will add another message here

**Comment by notBradPitt** [comment]
Thank you @Henrik-3, superb work! Would be interesting to see more filters in future updates (agents, etc.), but for now this is enough for me. Thanks! 😄
