### ISSUE TITLE
api.henrikdev.xyz/valorant/v1/mmr/ spaces in username

### ISSUE THREAD

**Issue by brokencommit** [Henrik-3/unofficial-valorant-api#36]
looks like v1 has issues with %20 in the username and tag

**Comment by Henrik-3** [comment]
Could u give me an example name where this happens?

**Comment by brokencommit** [comment]
https://api.henrikdev.xyz/valorant/v1/mmr/na/amouranth%20simp/1834
Is a random example I see where the api is failing

**Comment by Henrik-3** [comment]
He simply haven't a competitive match in his history, which means the current rank/mmr/elo can't be fetched, so it returns a 204 and has nothing to to do with spaces

**Comment by briantoe** [comment]
I checked out whether or not your library handles spaces about a week ago, the library works just fine 👍
