### ISSUE TITLE
/store-featured returns error 403

### ISSUE THREAD

**Issue by colinhartigan** [Henrik-3/unofficial-valorant-api#4]
![image](https://user-images.githubusercontent.com/42125428/109759394-f0432d80-7bba-11eb-9eb4-76802ccc1d93.png)

**Comment by Henrik-3** [comment]
Check again if it's still down, some parts of the API where down because of the new Act for about 2 Hours

**Comment by Henrik-3** [comment]
Seems to work again, I will close the issue then
