### ISSUE TITLE
c# open Api generator, exception on null for integers, from the specification

### ISSUE THREAD

**Issue by M-U-X** [Henrik-3/unofficial-valorant-api#41]
the api specifications defines non nullable integers for things like, stats headshot, legshots, bodyshots, and similar data that could have a value of null, resulting in exceptions on json deserialization, to replicate generate a client using openapi generator from the specification json file, and test it on a match with a player with 0 hs or any similar "nullable" integer

**Comment by Henrik-3** [comment]
I take a look at it

**Comment by M-U-X** [comment]
@Henrik-3 same for session playtime, match  "37d97018-a793-4080-8594-a02c051113c3" , players> allplayers[7], both seconds and millisecond are returned as null, and in fact minutes doesn't even exist
