### ISSUE TITLE
C# NSwag openapi/swagger generator conflict between player's Economy and round's playerstats' economy 

### ISSUE THREAD

**Issue by M-U-X** [Henrik-3/unofficial-valorant-api#44]
C# NSwag openapi/swagger generator conflict between player's Economy and round's playerstats' economy, the structure of a player's economy in a match details, is 
`spent {overall, average} loadout {overall, average}`
and in the round's playerstats is:
`spent: int,  loadout:int`
the generator uses the same structure for both since they have the same name "Economy", I don't know if that's an issue/limitation of the generator (unlikely) or an ambiguity of the openapi definitions of your API

**Comment by M-U-X** [comment]
Checking the swagger definition of the api, it's indeed an error on your part, 
`economy:
          type: object
          properties:
            spent:
              type: string
              properties:
                overall:
                  type: integer
                  example: 59750
                average:
                  type: integer
                  example: 2598
            loadout_value:
              type: object
              properties:
                overall:
                  type: integer
                  example: 71700
                average:
                  type: integer
                  example: 3117`
the type of spent is defined as string instead of object

**Comment by Henrik-3** [comment]
Should be fixed with v2.0.2
