### ISSUE TITLE
Unknown error in retrieving account

### ISSUE THREAD

**Issue by Azshurith** [Henrik-3/unofficial-valorant-api#52]
The getAccount/getMMR function currently returns Unknown error as message,
Here is the response message:
```
{
  status: 200,
  data: [ { message: 'Unknown error', code: 0, details: 'null' } ],
  ratelimits: { used: 3, remaining: 27, reset: 31 },
  error: null,
  url: 'https://api.henrikdev.xyz/valorant/v1/account/NRG%20Ethan/farm'
}
```

**Comment by raimannma** [comment]
Works for me

**Comment by Azshurith** [comment]
> Works for me

Are you using the latest version?

**Comment by Henrik-3** [comment]
I can check it in a couple of minutes, but I tested it before release and it worked. Maybe some edge case, idk, gonna verify and push a patch

**Comment by Henrik-3** [comment]
Recheck with the newest version please @Azshurith (2.2.1-stable.2)

**Comment by Azshurith** [comment]
Works great in my local! Thanks!
