### ISSUE TITLE
Bot news in Italian

### ISSUE THREAD

**Issue by KFR98** [Henrik-3/unofficial-valorant-api#59]
Hello,
I would like to know if it is possible to set the bot's news language in Italian, if this function is not yet available would it be possible to add it?
I can offer to make the changes in Italian.

**Comment by Henrik-3** [comment]
This is the wrong repository, but yes u can. 

Fork the `VALORANT-LABS` Repository and create a Pull Request with the changes in the following files:
- https://github.com/Henrik-3/valorant-labs/blob/v4/translations.json
- https://github.com/Henrik-3/valorant-labs/blob/v4/utils.json

Just copy paste the "en-us" part and change it to "it" and translate the sentences

**Comment by KFR98** [comment]
I translated the code you sent me, does it work?


Il giorno mer 21 set 2022 alle ore 17:42 Henrik Mertens <
***@***.***> ha scritto:

**Comment by Henrik-3** [comment]
Looks good, i am gonna check that out tommorow ^^

**Comment by Henrik-3** [comment]
Update online ^^
Gonna anounce it later that week

**Comment by KFR98** [comment]
@Henrik-3 So can you use the bot in Italian now or will it be updated this week?

**Comment by Henrik-3** [comment]
Is already possible, but not announced yet

**Comment by KFR98** [comment]
@Henrik-3 Perfect start testing it now!
