### ISSUE TITLE
[enhancement] endpoint for getting collection/bundle data from bundle uid

### ISSUE THREAD

**Issue by colinhartigan** [Henrik-3/unofficial-valorant-api#6]
not sure if it's possible with the data you have access to, but it would be nice if there was an endpoint that could return data like in [/valorant/v1/store-featured](https://api.henrikdev.xyz/valorant/v1/store-featured) from a uid rather than only the featured bundle

**Comment by Henrik-3** [comment]
If I understand you correctly, you want an Endpoint where you can get data about a certion guid, like a weapon guid and then the statistics and their skins etc. If u mean this take a look at https://valorant-api.com

**Comment by colinhartigan** [comment]
I mean a way to get the same structure of data as the featured collection endpoint (item id, price, quantity) but for other bundles (ex. get all contents of Prime 1.0 with prices, etc.)

valorant-api doesn’t contain this information which is why I suggested you look into it
 
you would not have to include images, upgrades, or image assets because those are already accessible from valorant-api

**Comment by Henrik-3** [comment]
There is no API where i can get the history of bundles, you can only get the data of all single offers https://api.henrikdev.xyz/valorant/v1/store-offers 

Eventually i find something interesting in the future but currently i don't know a way to get data of the bundles. If i find something i would leave a message here
