### ISSUE TITLE
Error using getMMR()

### ISSUE THREAD

**Issue by nicocespede** [Henrik-3/unofficial-valorant-api#60]
I'm getting `{"message":"A needed fetch request timed out three times, request will be terminated, please try again","code":0,"details":"null"}` or `{"message":"Riot Origin Server down for maintenance","code":0,"details":"null"}` when trying to get some accounts' MMR, but they're not consistent errors, they may appear randomly I'd say.

Here's my code snippet:

```
const accInfo = account.name.split('#');
const mmr = await ValorantAPI.getMMR({
     version: 'v1',
     region: 'latam',
     name: accInfo[0],
     tag: accInfo[1],
}).catch(console.error);
if (mmr.error) {
     [...]
     console.log(chalk.red('ValorantAPIError fetching ${account.name}:\n${JSON.stringify(mmr.error)}'));
     [...]
} else {
     [...]
}
```

Hope anyone can help me!

**Comment by pxzzo** [comment]
Same is happening to me.

It's a timeout between Riot and Henrik's servers, because the request could not be processed fast enough. There is not really much we can do, sadly.
