### ISSUE TITLE
All matches

### ISSUE THREAD

**Issue by Beltarm** [Henrik-3/unofficial-valorant-api#61]
Is there a way to get all my match history?

**Comment by Henrik-3** [comment]
No, also the official API does not have the entire history.
There will be an upcoming update that may can get close to a lifetime history, you will find more infos in the suggestions channel on the discord server: https://discord.gg/X3GaVkX2YN

**Comment by Henrik-3** [comment]
Coming soon: https://github.com/Henrik-3/unofficial-valorant-api/releases/tag/v2.7.0

**Comment by Henrik-3** [comment]
Deployed
