### ISSUE TITLE
Documentation is missing the kills field in match

### ISSUE THREAD

**Issue by suniastar** [Henrik-3/unofficial-valorant-api#68]
https://app.swaggerhub.com/apis-docs/Henrik-3/HenrikDev-API/3.0.0#/match is missing the documentation for the `kills` field.

**Comment by suniastar** [comment]
As far as I can tell the kills event field was moved from `match.rounds.player_stats.kill_events` to `kills`

**Comment by Henrik-3** [comment]
Was fixed in https://app.swaggerhub.com/apis-docs/Henrik-3/HenrikDev-API/3.0.1
