### ISSUE TITLE
[504] /valorant/v1/live-match problem with greek characters in name

### ISSUE THREAD

**Issue by tbitowt** [Henrik-3/unofficial-valorant-api#7]
While executing live-match endpoint while name contains Greek characters 504 is thrown

example URL:

[GET] https://api.henrikdev.xyz/valorant/v1/live-match/ΖμΙΜαη/666

Result:
504 - Gateway time-out

**Comment by Henrik-3** [comment]
Issue Resolved
Error Reason: Forgot to encode the name and tag before creating the request to the Ingame API Server
