### ISSUE TITLE
Documentation and Examples are not updated with API Key

### ISSUE THREAD

**Issue by iamNVN** [Henrik-3/unofficial-valorant-api#79]
Since the 3.0.1, API Key has been made mandatory. But the example for the usage of API Key hasn't been provided in the documentation nor the example codes.

**Comment by mr-velosofy** [comment]
@iamNVN 
Here are the two ways you can use the API key:

> ### 1.) As an Authorization Header
Include the API key in the request header as follows :
`Authorization: YOUR_API_KEY`

> ### 2.) Using URL Parameters
Pass the API key as a URL parameter :
`https://api.henrikdev.xyz/valorant/v1/account/ID/TAG?api_key=YOUR_API_KEY`

Hope he'll add soon it in the documentation

**Comment by mr-velosofy** [comment]
> Since the 3.0.1, API Key has been made mandatory. But the example for the usage of API Key hasn't been provided in the documentation nor the example codes.

@iamNVN 
Here are the two ways you can use the API key:

> ### 1.) As an Authorization Header
Include the API key in the request header as follows :
`Authorization: YOUR_API_KEY`

> ### 2.) Using URL Parameters
Pass the API key as a URL parameter :
`https://api.henrikdev.xyz/valorant/v1/account/ID/TAG?api_key=YOUR_API_KEY`

Hope he'll add soon it in the documentation

**Comment by iamNVN** [comment]
Thanks!
