### ISSUE TITLE
[GET] /valorant/v2/mmr/{region}/{name}/{tag} return wrong result while name has Greek characters

### ISSUE THREAD

**Issue by tbitowt** [Henrik-3/unofficial-valorant-api#8]
While executing /valorant/v2/mmr/{region}/{name}/{tag} while name has greek characters wrong data are returned in `current-data` field. It works fine for `v1` version.

It also works fine for non-greek characters

Example: 
[GET] https://api.henrikdev.xyz/valorant/v2/mmr/eu/ΖμΙΜαη/666

Result: 
```
{
    "status": "200",
    "data": {
        "current_data": {
            "currenttier": 0,
            "currenttierpatched": "Unrated",
            "ranking_in_tier": 0,
            "mmr_change_to_last_game": 0,
            "elo": -300,
            "games_needed_for_rating": 0
        },
...
```

**Comment by Henrik-3** [comment]
That is bug in RIOT's pvp.net API, when your last game is not competitive every value is zero, so not only greece names are affected
![image](https://user-images.githubusercontent.com/43936184/111868929-2b947900-897d-11eb-851d-40413e2f242c.png)

To fix this issue i will make a second request to another endpoint where i can get the latest movment for sure
