### ISSUE TITLE
API appears to be down 

### ISSUE THREAD

**Issue by themone10** [Henrik-3/unofficial-valorant-api#81]
API is not responding to any comand i give it to it

**Comment by Henrik-3** [comment]
Yes, riot changed some stuff in their authentication system again, you may want to check https://status.henrikdev.xyz/ regularly or join on the discord for updates

**Comment by themone10** [comment]
Thanks for the fast answer will be waiting for updates!

**Comment by Henrik-3** [comment]
Should be for now -.-
